/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type CitaDetalle = {
  id_cita?: string;
  doctor_nombre?: string;
  especialidad_etiqueta?: string;
  motivo_consulta?: string;
  estado_badge?: string;
  fecha_frase?: string;
  hora_formateada?: string;
  consultorio_numero?: string;
} & ({
  doctor_foto_url?: string;
  fecha_completa?: string;
  hora_formateada?: string;
  ubicacion_completa?: string;
  anticipo_monto?: string;
  /** @nullable */
  alerta_cancelacion?: {
  titulo?: string;
  mensaje?: string;
} | null;
  permitir_cancelacion?: boolean;
});
