/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type CrearCitaBody = {
  id_doctor: string;
  id_sucursal: string;
  fecha_hora_inicio: string;
  metodo_pago_id: string;
};
