/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { DisponibilidadHorariosPorDiaItem } from './disponibilidadHorariosPorDiaItem';

export interface Disponibilidad {
  /** Lista de fechas que tienen al menos un horario libre */
  dias_disponibles?: string[];
  /** Bloques de tiempo disponibles para la fecha seleccionada */
  horarios_por_dia?: DisponibilidadHorariosPorDiaItem[];
}
