/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerDoctoresPorEspecialidad200EspecialistasItem } from './obtenerDoctoresPorEspecialidad200EspecialistasItem';

export type ObtenerDoctoresPorEspecialidad200 = {
  especialistas?: ObtenerDoctoresPorEspecialidad200EspecialistasItem[];
};
