/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerDoctoresPorEspecialidad200EspecialistasItem = {
  id_doctor?: string;
  nombre_doctor?: string;
  foto_url?: string;
  calificacion_promedio?: number;
  experiencia_anios?: number;
  especialidad_titulo?: string;
};
