/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerAgendaDoctor200CitaDestacada = {
  id_cita?: string;
  doctor_nombre?: string;
  especialidad_etiqueta?: string;
  motivo_consulta?: string;
  estado_badge?: string;
  fecha_frase?: string;
  hora_formateada?: string;
  consultorio_numero?: string;
} & {
  paciente_nombre?: string;
  paciente_foto_url?: string;
};
