/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerHistorialMedicoPaciente200LineaTiempoConsultasItem = {
  id_historial?: string;
  fecha_formateada?: string;
  diagnostico_titulo?: string;
  resumen_notas?: string;
  tiene_resumen_medico?: boolean;
};
