/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerDisponibilidadDoctor200HorariosPorDiaItem } from './obtenerDisponibilidadDoctor200HorariosPorDiaItem';

export type ObtenerDisponibilidadDoctor200 = {
  dias_disponibles?: string[];
  horarios_por_dia?: ObtenerDisponibilidadDoctor200HorariosPorDiaItem[];
};
