/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerHistorialPagos200Meta } from './obtenerHistorialPagos200Meta';
import type { ObtenerHistorialPagos200PagosItem } from './obtenerHistorialPagos200PagosItem';
import type { ObtenerHistorialPagos200Resumen } from './obtenerHistorialPagos200Resumen';

export type ObtenerHistorialPagos200 = {
  resumen?: ObtenerHistorialPagos200Resumen;
  pagos?: ObtenerHistorialPagos200PagosItem[];
  meta?: ObtenerHistorialPagos200Meta;
};
