/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerSucursalesPorDoctor200SucursalesItemCoordenadas } from './obtenerSucursalesPorDoctor200SucursalesItemCoordenadas';

export type ObtenerSucursalesPorDoctor200SucursalesItem = {
  id_sucursal?: string;
  nombre_sucursal?: string;
  direccion_completa?: string;
  coordenadas?: ObtenerSucursalesPorDoctor200SucursalesItemCoordenadas;
};
