/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerAgendaDoctorPestana } from './obtenerAgendaDoctorPestana';

export type ObtenerAgendaDoctorParams = {
/**
 * Fecha seleccionada en el calendario (YYYY-MM-DD)
 */
fecha: string;
pestana: ObtenerAgendaDoctorPestana;
};
