/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerInicioPaciente200NextCita } from './obtenerInicioPaciente200NextCita';
import type { ObtenerInicioPaciente200QuickActionsItem } from './obtenerInicioPaciente200QuickActionsItem';

export type ObtenerInicioPaciente200 = {
  nombre_pila?: string;
  foto_perfil_url?: string;
  estado_salud_resumen?: string;
  next_cita?: ObtenerInicioPaciente200NextCita;
  quick_actions?: ObtenerInicioPaciente200QuickActionsItem[];
};
