/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerHistorialMedicoPaciente200LineaTiempoConsultasItem } from './obtenerHistorialMedicoPaciente200LineaTiempoConsultasItem';
import type { ObtenerHistorialMedicoPaciente200Meta } from './obtenerHistorialMedicoPaciente200Meta';

export type ObtenerHistorialMedicoPaciente200 = {
  linea_tiempo_consultas?: ObtenerHistorialMedicoPaciente200LineaTiempoConsultasItem[];
  meta?: ObtenerHistorialMedicoPaciente200Meta;
};
