/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerDoctoresPorEspecialidadYSucursal200EspecialistasItem } from './obtenerDoctoresPorEspecialidadYSucursal200EspecialistasItem';

export type ObtenerDoctoresPorEspecialidadYSucursal200 = {
  especialistas?: ObtenerDoctoresPorEspecialidadYSucursal200EspecialistasItem[];
};
