/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerPagosDoctor200TransaccionesRecientesItemEstatus = typeof ObtenerPagosDoctor200TransaccionesRecientesItemEstatus[keyof typeof ObtenerPagosDoctor200TransaccionesRecientesItemEstatus];


export const ObtenerPagosDoctor200TransaccionesRecientesItemEstatus = {
  PAGADO: 'PAGADO',
  PENDIENTE: 'PENDIENTE',
} as const;
