/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerPerfilPaciente200 = {
  id_paciente?: string;
  nombre_completo?: string;
  nombre_pila?: string;
  foto_perfil_url?: string;
  correo_electronico?: string;
  fecha_nacimiento?: string;
  peso?: number;
  altura?: number;
  tipo_sangre?: string;
  telefono?: string;
  direccion_completa?: string;
};
