/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerHistorialPagos200PagosItemEstatus = typeof ObtenerHistorialPagos200PagosItemEstatus[keyof typeof ObtenerHistorialPagos200PagosItemEstatus];


export const ObtenerHistorialPagos200PagosItemEstatus = {
  PAGADO: 'PAGADO',
  PENDIENTE: 'PENDIENTE',
} as const;
