/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerResumenReserva200 = {
  doctor_nombre?: string;
  doctor_foto_url?: string;
  especialidad_titulo?: string;
  sucursal_nombre?: string;
  sucursal_direccion?: string;
  fecha_hora_formateada?: string;
  duracion_estimada?: string;
  costo_total?: string;
  anticipo_requerido?: string;
};
