/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerExpedientePaciente200HistorialItem = {
  /** ID de la consulta para ir al detalle completo */
  id: string;
  /** Fecha formateada o ISO (ej. 15 DE AGOSTO, 2023) */
  fecha: string;
  /** Motivo principal o diagnóstico (ej. Faringitis Aguda) */
  titulo: string;
  /** Breve descripción o notas principales de la consulta */
  resumen: string;
};
