/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerPagosDoctor200TransaccionesRecientesItemEstadoPago = typeof ObtenerPagosDoctor200TransaccionesRecientesItemEstadoPago[keyof typeof ObtenerPagosDoctor200TransaccionesRecientesItemEstadoPago];


export const ObtenerPagosDoctor200TransaccionesRecientesItemEstadoPago = {
  PAGADO: 'PAGADO',
  PENDIENTE: 'PENDIENTE',
  RECHAZADO: 'RECHAZADO',
  REEMBOLSADO: 'REEMBOLSADO',
} as const;
