/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerHistorialPagosEstatus } from './obtenerHistorialPagosEstatus';

export type ObtenerHistorialPagosParams = {
/**
 * Cantidad de registros por página
 */
limit?: number;
/**
 * Número de página a consultar
 */
page?: number;
/**
 * Filtra la lista por PENDIENTE o PAGADO
 */
estatus: ObtenerHistorialPagosEstatus;
};
