/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export interface PacienteResumen {
  id: string;
  nombre: string;
  /** Fecha o información de la última sesión con el paciente */
  ultima_consulta: string;
  avatar_url?: string;
}
