/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type PostV1AuthSignup201Rol = typeof PostV1AuthSignup201Rol[keyof typeof PostV1AuthSignup201Rol];


export const PostV1AuthSignup201Rol = {
  PACIENTE: 'PACIENTE',
  DOCTOR: 'DOCTOR',
} as const;
