/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { TransaccionEstadoPago } from './transaccionEstadoPago';

export interface Transaccion {
  id_transaccion?: string;
  titulo_concepto?: string;
  fecha_formateada?: string;
  monto_formateado?: string;
  estado_pago?: TransaccionEstadoPago;
  icono_concepto?: string;
}
