/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PostV1AuthLogin200,
  PostV1AuthLogin401,
  PostV1AuthLoginBody
} from '../models';

import { customInstance } from '.././axios-instance';




/**
 * @summary Iniciar sesión en el sistema
 */
export const postV1AuthLogin = (
    postV1AuthLoginBody: PostV1AuthLoginBody,
 signal?: AbortSignal
) => {


      return customInstance<PostV1AuthLogin200>(
      {url: `/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1AuthLoginBody, signal
    },
      );
    }



export const getPostV1AuthLoginMutationOptions = <TError = PostV1AuthLogin401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: PostV1AuthLoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: PostV1AuthLoginBody}, TContext> => {

const mutationKey = ['postV1AuthLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthLogin>>, {data: PostV1AuthLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogin>>>
    export type PostV1AuthLoginMutationBody = PostV1AuthLoginBody
    export type PostV1AuthLoginMutationError = PostV1AuthLogin401

    /**
 * @summary Iniciar sesión en el sistema
 */
export const usePostV1AuthLogin = <TError = PostV1AuthLogin401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: PostV1AuthLoginBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthLogin>>,
        TError,
        {data: PostV1AuthLoginBody},
        TContext
      > => {
      return useMutation(getPostV1AuthLoginMutationOptions(options), queryClient);
    }
