/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export interface ExpedienteClinico {
  id_paciente?: string;
  notas_interrogatorio?: string;
  notas_exploracion_fisica?: string;
  notas_diagnostico?: string;
  notas_tratamiento_receta?: string;
  archivos_adjuntos?: string[];
  consentimiento_firmado?: boolean;
}
