/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerPacientesDoctor200PacientesRecientesItem = {
  id_paciente?: string;
  foto_perfil_url?: string;
  nombre_completo?: string;
  id_paciente_corto?: string;
  indicador_estado?: boolean;
  cita_info_resumen?: string;
};
