/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerPagosDoctor200TransaccionesRecientesItemEstadoPago } from './obtenerPagosDoctor200TransaccionesRecientesItemEstadoPago';

export type ObtenerPagosDoctor200TransaccionesRecientesItem = {
  id_transaccion?: string;
  titulo_concepto?: string;
  fecha_formateada?: string;
  monto_formateado?: string;
  estado_pago?: ObtenerPagosDoctor200TransaccionesRecientesItemEstadoPago;
  icono_concepto?: string;
};
