/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerCitasProximasPaciente200CompletadasRecientementeItem } from './obtenerCitasProximasPaciente200CompletadasRecientementeItem';
import type { ObtenerCitasProximasPaciente200ProximaPrioridad } from './obtenerCitasProximasPaciente200ProximaPrioridad';
import type { ObtenerCitasProximasPaciente200VisitasProximasItem } from './obtenerCitasProximasPaciente200VisitasProximasItem';

export type ObtenerCitasProximasPaciente200 = {
  proxima_prioridad?: ObtenerCitasProximasPaciente200ProximaPrioridad;
  visitas_proximas?: ObtenerCitasProximasPaciente200VisitasProximasItem[];
  completadas_recientemente?: ObtenerCitasProximasPaciente200CompletadasRecientementeItem[];
};
