/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerAgendaDoctor200CitaDestacada } from './obtenerAgendaDoctor200CitaDestacada';
import type { ObtenerAgendaDoctor200FinalizadasHoyItem } from './obtenerAgendaDoctor200FinalizadasHoyItem';
import type { ObtenerAgendaDoctor200RestoDelDiaItem } from './obtenerAgendaDoctor200RestoDelDiaItem';

export type ObtenerAgendaDoctor200 = {
  cita_destacada?: ObtenerAgendaDoctor200CitaDestacada;
  resto_del_dia?: ObtenerAgendaDoctor200RestoDelDiaItem[];
  finalizadas_hoy?: ObtenerAgendaDoctor200FinalizadasHoyItem[];
};
