/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerInicioPaciente200QuickActionsItem = {
  action_id?: string;
  label?: string;
  icon_id?: string;
  route_name?: string;
  is_enabled?: boolean;
};
