/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerDatosNuevaConsulta200 = {
  paciente_nombre?: string;
  paciente_foto_url?: string;
  id_paciente_formateado?: string;
  edad_anios?: number;
  peso_kg?: number;
  alergias_resumen?: string;
};
