/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */

export type ObtenerPerfilDoctor200 = {
  foto_perfil_url?: string;
  nombre_display?: string;
  nivel_especialista?: string;
  especialidad?: string;
  experiencia_anios?: number;
  nombre_completo?: string;
  cedula_profesional?: string;
  fecha_nacimiento?: string;
  telefono?: string;
  correo_electronico?: string;
};
