/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerPacientesDoctor200PacientesRecientesItem } from './obtenerPacientesDoctor200PacientesRecientesItem';

export type ObtenerPacientesDoctor200 = {
  pacientes_recientes?: ObtenerPacientesDoctor200PacientesRecientesItem[];
};
