/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { ObtenerPagosDoctor200TransaccionesRecientesItem } from './obtenerPagosDoctor200TransaccionesRecientesItem';

export type ObtenerPagosDoctor200 = {
  ingresos_del_mes_formateado?: string;
  transacciones_recientes?: ObtenerPagosDoctor200TransaccionesRecientesItem[];
};
