/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { PostV1AuthLogin200Rol } from './postV1AuthLogin200Rol';

export type PostV1AuthLogin200 = {
  /** JWT para autenticar peticiones */
  token?: string;
  rol?: PostV1AuthLogin200Rol;
  usuario_id?: string;
};
