/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import type { PostV1DoctorBloquearAgendaBodyIdUbicacion } from './postV1DoctorBloquearAgendaBodyIdUbicacion';

export type PostV1DoctorBloquearAgendaBody = {
  id_ubicacion: PostV1DoctorBloquearAgendaBodyIdUbicacion;
  fechas_seleccionadas: string[];
  bloquear_todo_el_dia?: boolean;
  hora_inicio?: string;
  hora_fin?: string;
  motivo_bloqueo?: string;
};
