/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ObtenerCitasPasadasPaciente200,
  ObtenerCitasPasadasPaciente401,
  ObtenerCitasProximasPaciente200,
  ObtenerCitasProximasPaciente401,
  ObtenerDetallesCitaPaciente200,
  ObtenerDetallesCitaPaciente401,
  ObtenerDetallesCitaPacienteParams,
  ObtenerDisponibilidadDoctor200,
  ObtenerDisponibilidadDoctorParams,
  ObtenerDoctoresPorEspecialidadYSucursal200,
  ObtenerDoctoresPorEspecialidadYSucursalParams,
  ObtenerEspecialidades200,
  ObtenerHistorialMedicoPaciente200,
  ObtenerHistorialMedicoPaciente401,
  ObtenerHistorialPagosPaciente200,
  ObtenerHistorialPagosPaciente401,
  ObtenerInicioPaciente200,
  ObtenerInicioPaciente401,
  ObtenerPerfilPaciente200,
  ObtenerPerfilPaciente401,
  ObtenerResumenReserva200,
  ObtenerResumenReservaParams,
  ObtenerSucursales200
} from '../model';

import { customInstance } from '.././axios-instance';




/**
 * @summary Obtener datos para la pantalla de inicio del paciente
 */
export const obtenerInicioPaciente = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerInicioPaciente200>(
      {url: `/v1/views/paciente/home`, method: 'GET', signal
    },
      );
    }




export const getObtenerInicioPacienteQueryKey = () => {
    return [
    `/v1/views/paciente/home`
    ] as const;
    }


export const getObtenerInicioPacienteQueryOptions = <TData = Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError = ObtenerInicioPaciente401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerInicioPacienteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerInicioPaciente>>> = ({ signal }) => obtenerInicioPaciente(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerInicioPacienteQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerInicioPaciente>>>
export type ObtenerInicioPacienteQueryError = ObtenerInicioPaciente401


export function useObtenerInicioPaciente<TData = Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError = ObtenerInicioPaciente401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerInicioPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerInicioPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerInicioPaciente<TData = Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError = ObtenerInicioPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerInicioPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerInicioPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerInicioPaciente<TData = Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError = ObtenerInicioPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener datos para la pantalla de inicio del paciente
 */

export function useObtenerInicioPaciente<TData = Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError = ObtenerInicioPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerInicioPacienteQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Información personal y de contacto del paciente
 */
export const obtenerPerfilPaciente = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerPerfilPaciente200>(
      {url: `/v1/views/paciente/perfil_paciente`, method: 'GET', signal
    },
      );
    }




export const getObtenerPerfilPacienteQueryKey = () => {
    return [
    `/v1/views/paciente/perfil_paciente`
    ] as const;
    }


export const getObtenerPerfilPacienteQueryOptions = <TData = Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError = ObtenerPerfilPaciente401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerPerfilPacienteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerPerfilPaciente>>> = ({ signal }) => obtenerPerfilPaciente(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerPerfilPacienteQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerPerfilPaciente>>>
export type ObtenerPerfilPacienteQueryError = ObtenerPerfilPaciente401


export function useObtenerPerfilPaciente<TData = Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError = ObtenerPerfilPaciente401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerPerfilPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerPerfilPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerPerfilPaciente<TData = Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError = ObtenerPerfilPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerPerfilPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerPerfilPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerPerfilPaciente<TData = Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError = ObtenerPerfilPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Información personal y de contacto del paciente
 */

export function useObtenerPerfilPaciente<TData = Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError = ObtenerPerfilPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerPerfilPacienteQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Listado de citas próximas y recientes
 */
export const obtenerCitasProximasPaciente = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerCitasProximasPaciente200>(
      {url: `/v1/views/paciente/citas_proximas`, method: 'GET', signal
    },
      );
    }




export const getObtenerCitasProximasPacienteQueryKey = () => {
    return [
    `/v1/views/paciente/citas_proximas`
    ] as const;
    }


export const getObtenerCitasProximasPacienteQueryOptions = <TData = Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError = ObtenerCitasProximasPaciente401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerCitasProximasPacienteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>> = ({ signal }) => obtenerCitasProximasPaciente(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerCitasProximasPacienteQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>>
export type ObtenerCitasProximasPacienteQueryError = ObtenerCitasProximasPaciente401


export function useObtenerCitasProximasPaciente<TData = Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError = ObtenerCitasProximasPaciente401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerCitasProximasPaciente<TData = Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError = ObtenerCitasProximasPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerCitasProximasPaciente<TData = Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError = ObtenerCitasProximasPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listado de citas próximas y recientes
 */

export function useObtenerCitasProximasPaciente<TData = Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError = ObtenerCitasProximasPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasProximasPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerCitasProximasPacienteQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Historial completo de citas finalizadas
 */
export const obtenerCitasPasadasPaciente = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerCitasPasadasPaciente200>(
      {url: `/v1/views/paciente/citas_pasadas`, method: 'GET', signal
    },
      );
    }




export const getObtenerCitasPasadasPacienteQueryKey = () => {
    return [
    `/v1/views/paciente/citas_pasadas`
    ] as const;
    }


export const getObtenerCitasPasadasPacienteQueryOptions = <TData = Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError = ObtenerCitasPasadasPaciente401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerCitasPasadasPacienteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>> = ({ signal }) => obtenerCitasPasadasPaciente(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerCitasPasadasPacienteQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>>
export type ObtenerCitasPasadasPacienteQueryError = ObtenerCitasPasadasPaciente401


export function useObtenerCitasPasadasPaciente<TData = Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError = ObtenerCitasPasadasPaciente401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerCitasPasadasPaciente<TData = Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError = ObtenerCitasPasadasPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerCitasPasadasPaciente<TData = Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError = ObtenerCitasPasadasPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Historial completo de citas finalizadas
 */

export function useObtenerCitasPasadasPaciente<TData = Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError = ObtenerCitasPasadasPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerCitasPasadasPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerCitasPasadasPacienteQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Detalles y gestión de una cita específica
 */
export const obtenerDetallesCitaPaciente = (
    params: ObtenerDetallesCitaPacienteParams,
 signal?: AbortSignal
) => {


      return customInstance<ObtenerDetallesCitaPaciente200>(
      {url: `/v1/views/paciente/gestionar_cita`, method: 'GET',
        params, signal
    },
      );
    }




export const getObtenerDetallesCitaPacienteQueryKey = (params?: ObtenerDetallesCitaPacienteParams,) => {
    return [
    `/v1/views/paciente/gestionar_cita`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerDetallesCitaPacienteQueryOptions = <TData = Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError = ObtenerDetallesCitaPaciente401>(params: ObtenerDetallesCitaPacienteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerDetallesCitaPacienteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>> = ({ signal }) => obtenerDetallesCitaPaciente(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerDetallesCitaPacienteQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>>
export type ObtenerDetallesCitaPacienteQueryError = ObtenerDetallesCitaPaciente401


export function useObtenerDetallesCitaPaciente<TData = Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError = ObtenerDetallesCitaPaciente401>(
 params: ObtenerDetallesCitaPacienteParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerDetallesCitaPaciente<TData = Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError = ObtenerDetallesCitaPaciente401>(
 params: ObtenerDetallesCitaPacienteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerDetallesCitaPaciente<TData = Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError = ObtenerDetallesCitaPaciente401>(
 params: ObtenerDetallesCitaPacienteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Detalles y gestión de una cita específica
 */

export function useObtenerDetallesCitaPaciente<TData = Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError = ObtenerDetallesCitaPaciente401>(
 params: ObtenerDetallesCitaPacienteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDetallesCitaPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerDetallesCitaPacienteQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Paso 1: Lista de especialidades
 */
export const obtenerEspecialidades = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerEspecialidades200>(
      {url: `/v1/views/paciente/reservas/especialidades`, method: 'GET', signal
    },
      );
    }




export const getObtenerEspecialidadesQueryKey = () => {
    return [
    `/v1/views/paciente/reservas/especialidades`
    ] as const;
    }


export const getObtenerEspecialidadesQueryOptions = <TData = Awaited<ReturnType<typeof obtenerEspecialidades>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEspecialidades>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerEspecialidadesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerEspecialidades>>> = ({ signal }) => obtenerEspecialidades(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerEspecialidades>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerEspecialidadesQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerEspecialidades>>>
export type ObtenerEspecialidadesQueryError = unknown


export function useObtenerEspecialidades<TData = Awaited<ReturnType<typeof obtenerEspecialidades>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEspecialidades>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerEspecialidades>>,
          TError,
          Awaited<ReturnType<typeof obtenerEspecialidades>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerEspecialidades<TData = Awaited<ReturnType<typeof obtenerEspecialidades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEspecialidades>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerEspecialidades>>,
          TError,
          Awaited<ReturnType<typeof obtenerEspecialidades>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerEspecialidades<TData = Awaited<ReturnType<typeof obtenerEspecialidades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEspecialidades>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paso 1: Lista de especialidades
 */

export function useObtenerEspecialidades<TData = Awaited<ReturnType<typeof obtenerEspecialidades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEspecialidades>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerEspecialidadesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Paso 2: Selección de clínica más cercana
 */
export const obtenerSucursales = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerSucursales200>(
      {url: `/v1/views/paciente/reservas/sucursales`, method: 'GET', signal
    },
      );
    }




export const getObtenerSucursalesQueryKey = () => {
    return [
    `/v1/views/paciente/reservas/sucursales`
    ] as const;
    }


export const getObtenerSucursalesQueryOptions = <TData = Awaited<ReturnType<typeof obtenerSucursales>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerSucursales>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerSucursalesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerSucursales>>> = ({ signal }) => obtenerSucursales(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerSucursales>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerSucursalesQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerSucursales>>>
export type ObtenerSucursalesQueryError = unknown


export function useObtenerSucursales<TData = Awaited<ReturnType<typeof obtenerSucursales>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerSucursales>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerSucursales>>,
          TError,
          Awaited<ReturnType<typeof obtenerSucursales>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerSucursales<TData = Awaited<ReturnType<typeof obtenerSucursales>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerSucursales>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerSucursales>>,
          TError,
          Awaited<ReturnType<typeof obtenerSucursales>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerSucursales<TData = Awaited<ReturnType<typeof obtenerSucursales>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerSucursales>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paso 2: Selección de clínica más cercana
 */

export function useObtenerSucursales<TData = Awaited<ReturnType<typeof obtenerSucursales>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerSucursales>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerSucursalesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Paso 3: Especialistas por sucursal y área
 */
export const obtenerDoctoresPorEspecialidadYSucursal = (
    params: ObtenerDoctoresPorEspecialidadYSucursalParams,
 signal?: AbortSignal
) => {


      return customInstance<ObtenerDoctoresPorEspecialidadYSucursal200>(
      {url: `/v1/views/paciente/reservas/doctores`, method: 'GET',
        params, signal
    },
      );
    }




export const getObtenerDoctoresPorEspecialidadYSucursalQueryKey = (params?: ObtenerDoctoresPorEspecialidadYSucursalParams,) => {
    return [
    `/v1/views/paciente/reservas/doctores`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerDoctoresPorEspecialidadYSucursalQueryOptions = <TData = Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError = unknown>(params: ObtenerDoctoresPorEspecialidadYSucursalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerDoctoresPorEspecialidadYSucursalQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>> = ({ signal }) => obtenerDoctoresPorEspecialidadYSucursal(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerDoctoresPorEspecialidadYSucursalQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>>
export type ObtenerDoctoresPorEspecialidadYSucursalQueryError = unknown


export function useObtenerDoctoresPorEspecialidadYSucursal<TData = Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError = unknown>(
 params: ObtenerDoctoresPorEspecialidadYSucursalParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>,
          TError,
          Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerDoctoresPorEspecialidadYSucursal<TData = Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError = unknown>(
 params: ObtenerDoctoresPorEspecialidadYSucursalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>,
          TError,
          Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerDoctoresPorEspecialidadYSucursal<TData = Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError = unknown>(
 params: ObtenerDoctoresPorEspecialidadYSucursalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paso 3: Especialistas por sucursal y área
 */

export function useObtenerDoctoresPorEspecialidadYSucursal<TData = Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError = unknown>(
 params: ObtenerDoctoresPorEspecialidadYSucursalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDoctoresPorEspecialidadYSucursal>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerDoctoresPorEspecialidadYSucursalQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Paso 4: Calendario de horarios libres
 */
export const obtenerDisponibilidadDoctor = (
    params: ObtenerDisponibilidadDoctorParams,
 signal?: AbortSignal
) => {


      return customInstance<ObtenerDisponibilidadDoctor200>(
      {url: `/v1/views/paciente/reservas/disponibilidad`, method: 'GET',
        params, signal
    },
      );
    }




export const getObtenerDisponibilidadDoctorQueryKey = (params?: ObtenerDisponibilidadDoctorParams,) => {
    return [
    `/v1/views/paciente/reservas/disponibilidad`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerDisponibilidadDoctorQueryOptions = <TData = Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError = unknown>(params: ObtenerDisponibilidadDoctorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerDisponibilidadDoctorQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>> = ({ signal }) => obtenerDisponibilidadDoctor(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerDisponibilidadDoctorQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>>
export type ObtenerDisponibilidadDoctorQueryError = unknown


export function useObtenerDisponibilidadDoctor<TData = Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError = unknown>(
 params: ObtenerDisponibilidadDoctorParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerDisponibilidadDoctor<TData = Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError = unknown>(
 params: ObtenerDisponibilidadDoctorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerDisponibilidadDoctor<TData = Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError = unknown>(
 params: ObtenerDisponibilidadDoctorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paso 4: Calendario de horarios libres
 */

export function useObtenerDisponibilidadDoctor<TData = Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError = unknown>(
 params: ObtenerDisponibilidadDoctorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDisponibilidadDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerDisponibilidadDoctorQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Paso 5: Resumen final para confirmación
 */
export const obtenerResumenReserva = (
    params: ObtenerResumenReservaParams,
 signal?: AbortSignal
) => {


      return customInstance<ObtenerResumenReserva200>(
      {url: `/v1/views/paciente/reservas/resumen`, method: 'GET',
        params, signal
    },
      );
    }




export const getObtenerResumenReservaQueryKey = (params?: ObtenerResumenReservaParams,) => {
    return [
    `/v1/views/paciente/reservas/resumen`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerResumenReservaQueryOptions = <TData = Awaited<ReturnType<typeof obtenerResumenReserva>>, TError = unknown>(params: ObtenerResumenReservaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenReserva>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerResumenReservaQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerResumenReserva>>> = ({ signal }) => obtenerResumenReserva(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenReserva>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerResumenReservaQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerResumenReserva>>>
export type ObtenerResumenReservaQueryError = unknown


export function useObtenerResumenReserva<TData = Awaited<ReturnType<typeof obtenerResumenReserva>>, TError = unknown>(
 params: ObtenerResumenReservaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenReserva>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerResumenReserva>>,
          TError,
          Awaited<ReturnType<typeof obtenerResumenReserva>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerResumenReserva<TData = Awaited<ReturnType<typeof obtenerResumenReserva>>, TError = unknown>(
 params: ObtenerResumenReservaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenReserva>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerResumenReserva>>,
          TError,
          Awaited<ReturnType<typeof obtenerResumenReserva>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerResumenReserva<TData = Awaited<ReturnType<typeof obtenerResumenReserva>>, TError = unknown>(
 params: ObtenerResumenReservaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenReserva>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paso 5: Resumen final para confirmación
 */

export function useObtenerResumenReserva<TData = Awaited<ReturnType<typeof obtenerResumenReserva>>, TError = unknown>(
 params: ObtenerResumenReservaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenReserva>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerResumenReservaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Línea de tiempo de diagnósticos y consultas
 */
export const obtenerHistorialMedicoPaciente = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerHistorialMedicoPaciente200>(
      {url: `/v1/views/paciente/historial_medico`, method: 'GET', signal
    },
      );
    }




export const getObtenerHistorialMedicoPacienteQueryKey = () => {
    return [
    `/v1/views/paciente/historial_medico`
    ] as const;
    }


export const getObtenerHistorialMedicoPacienteQueryOptions = <TData = Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError = ObtenerHistorialMedicoPaciente401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerHistorialMedicoPacienteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>> = ({ signal }) => obtenerHistorialMedicoPaciente(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerHistorialMedicoPacienteQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>>
export type ObtenerHistorialMedicoPacienteQueryError = ObtenerHistorialMedicoPaciente401


export function useObtenerHistorialMedicoPaciente<TData = Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError = ObtenerHistorialMedicoPaciente401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerHistorialMedicoPaciente<TData = Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError = ObtenerHistorialMedicoPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerHistorialMedicoPaciente<TData = Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError = ObtenerHistorialMedicoPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Línea de tiempo de diagnósticos y consultas
 */

export function useObtenerHistorialMedicoPaciente<TData = Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError = ObtenerHistorialMedicoPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialMedicoPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerHistorialMedicoPacienteQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Control financiero y adeudos pendientes
 */
export const obtenerHistorialPagosPaciente = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerHistorialPagosPaciente200>(
      {url: `/v1/views/paciente/historial_pagos`, method: 'GET', signal
    },
      );
    }




export const getObtenerHistorialPagosPacienteQueryKey = () => {
    return [
    `/v1/views/paciente/historial_pagos`
    ] as const;
    }


export const getObtenerHistorialPagosPacienteQueryOptions = <TData = Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError = ObtenerHistorialPagosPaciente401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerHistorialPagosPacienteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>> = ({ signal }) => obtenerHistorialPagosPaciente(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerHistorialPagosPacienteQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>>
export type ObtenerHistorialPagosPacienteQueryError = ObtenerHistorialPagosPaciente401


export function useObtenerHistorialPagosPaciente<TData = Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError = ObtenerHistorialPagosPaciente401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerHistorialPagosPaciente<TData = Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError = ObtenerHistorialPagosPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>,
          TError,
          Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerHistorialPagosPaciente<TData = Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError = ObtenerHistorialPagosPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Control financiero y adeudos pendientes
 */

export function useObtenerHistorialPagosPaciente<TData = Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError = ObtenerHistorialPagosPaciente401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPagosPaciente>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerHistorialPagosPacienteQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






