### Variables
@baseUrl = http://localhost:3000/api

###Token falso para probar que nuestro escudo rechaza intrusos
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.falso.falso

### 1. Probar el servidor (Ruta Pública)
GET {{baseUrl}}/ping

### 2. Probar ruta protegida SIN Token (Debería devolver 401 UNAUTHORIZED)
GET {{baseUrl}}/v1/views/patient/home

### 3. Probar ruta protegida CON Token inválido (Debería devolver 401 INVALID_TOKEN)
GET {{baseUrl}}/v1/views/patient/home
Authorization: Bearer {{token}}

### 4. Probar captura de errores (Debería devolver un 400 estandarizado)
GET {{baseUrl}}/error

### 5. Generar un Token Válido (Simulando un Login)
GET {{baseUrl}}/test-login

### --------------------------------------------------------
### Pega el token que te devolvió la prueba 5 aquí abajo 👇
@validToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkZWY4N2M0LWZlNzgtNDIyYy1hMTU2LTRkNGQyNTkyZjE2MyIsImlkX3BhY2llbnRlIjoiYWRlZjg3YzQtZmU3OC00MjJjLWExNTYtNGQ0ZDI1OTJmMTYzIiwicm9sIjoiUEFDSUVOVEUiLCJpYXQiOjE3Nzc0NzI3OTUsImV4cCI6MTc3NzU1OTE5NX0.dnu-3ksMqYPg1viSpN0Ue1y4BaZ8CO5dXCd6I2aHx60
### --------------------------------------------------------

### 6. Probar ruta protegida CON Token Válido (¡El Happy Path!)
GET {{baseUrl}}/v1/views/patient/home
Authorization: Bearer {{validToken}}

### 7. Probar Citas Próximas
GET {{baseUrl}}/v1/views/patient/citas_proximas
Authorization: Bearer {{validToken}}

### 8. Probar Citas Pasadas 
GET {{baseUrl}}/v1/views/patient/citas_pasadas?page=1&limit=1
Authorization: Bearer {{validToken}}

### 9. Probar Mi Perfil
GET {{baseUrl}}/v1/views/patient/profile_details
Authorization: Bearer {{validToken}}

### 10. Probar Historial Médico
GET {{baseUrl}}/v1/views/patient/historial_medico
Authorization: Bearer {{validToken}}

### 11. Probar Historial de Pagos
GET {{baseUrl}}/v1/views/patient/historial_pagos
Authorization: Bearer {{validToken}}

### ==========================================
### FLUJO DE RESERVA MÉDICA
### ==========================================

### 12. Paso 1: Especialidades
GET {{baseUrl}}/v1/views/patient/reservas/especialidad
Authorization: Bearer {{validToken}}

### 13. Paso 2: Sucursales
GET {{baseUrl}}/v1/views/patient/reservas/sucursal
Authorization: Bearer {{validToken}}

### 14. Paso 3: Doctores
GET {{baseUrl}}/v1/views/patient/reservas/doctores?especialidad_id=159ee91c-5f5a-4bcd-af6f-6cf8d97e7345&sucursal_id=23e11d57-2b0e-4e46-991b-668e31efc837
Authorization: Bearer {{validToken}}

### 15. Paso 4: Disponibilidad
GET {{baseUrl}}/v1/views/patient/reservas/disponibilidad?id_doctor=09b215ef-6ab4-43e1-a978-a68c55e84d0c
Authorization: Bearer {{validToken}}

### 16. Paso 5: Resumen Final
GET {{baseUrl}}/v1/views/patient/reservas/resumen?id_doctor=be668ee7-58af-4d7b-9a1e-64ab97d80fd3&id_sucursal=23e11d57-2b0e-4e46-991b-668e31efc837&fecha_hora_inicio=2026-04-27T10:00:00.000Z
Authorization: Bearer {{validToken}}

### ==========================================
### ACCIONES Y MUTACIONES DEL PACIENTE
### ==========================================

### 17. Actualizar Perfil (PUT)
PUT {{baseUrl}}/v1/patient/profile
Authorization: Bearer {{validToken}}
Content-Type: application/json

{
    "peso": 85.5,
    "altura": 1.80,
    "telefono": "+52 55 1234 5678",
    "direccion_completa": "Nueva Dirección 456, Ciudad"
}

### 18. Confirmar Reserva y Pagar Anticipo (POST)
POST {{baseUrl}}/v1/reservas/appointments
Authorization: Bearer {{validToken}}
Content-Type: application/json

{
    "id_doctor": "f700318f-3f60-4833-9c8f-45c1162a20a8",
    "id_sucursal": "23e11d57-2b0e-4e46-991b-668e31efc837",
    "fecha_hora_inicio": "2026-04-28T10:00:00.000Z",
    "metodo_pago_id": "pago_en_clinica"
}

### 19. Pagar Adeudo Pendiente (POST)
POST {{baseUrl}}/v1/patient/historial_pagos/t1u2v3w4-x5y6-z789-0abc-def123456789/pay
Authorization: Bearer {{validToken}}
Content-Type: application/json

{
    "metodo_pago_id": "card_9876"
}

### 20. Cancelar Cita (PATCH)
PATCH {{baseUrl}}/v1/appointments/567ba3b3-0acd-4577-a055-c79bb073f4b5/cancel
Authorization: Bearer {{validToken}}
Content-Type: application/json

{
    "motivo_cancelacion": "Me surgió un viaje de trabajo inesperado"
}

### 21. Prueba de Escudo de Errores (500 Internal Server Error)
GET {{baseUrl}}/v1/crash-test

### ==========================================
### MÓDULO DE AUTENTICACIÓN (REAL)
### ==========================================

### 1. Registrar un nuevo usuario (Crea Usuario + Perfil)
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
    "nombre_completo": "Angel Gabriel Roman Zazueta",
    "correo_electronico": "angel.test@atria.com",
    "password": "password123",
    "fecha_nacimiento": "2000-01-01T00:00:00Z",
    "telefono": "6675152646",
    "sexo_biologico": "M",
    "tipo_sangre": "O+",
    "rol": "DOCTOR"
}

### 2. Iniciar Sesión (Login)
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{
    "correo_electronico": "angel.test@atria.com",
    "password": "password123"
}