/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ActualizarPerfilPaciente200,
  ActualizarPerfilPaciente400,
  ActualizarPerfilPaciente401,
  ActualizarPerfilPacienteBody,
  CancelarCita200,
  CancelarCita400,
  CancelarCita401,
  CancelarCitaBody,
  CrearCita201,
  CrearCita400,
  CrearCita401,
  CrearCitaBody,
  PagarTransaccionPendiente200,
  PagarTransaccionPendiente400,
  PagarTransaccionPendiente401,
  PagarTransaccionPendienteBody
} from '../model';

import { customInstance } from '.././axios-instance';




/**
 * @summary Actualizar la información del perfil del paciente
 */
export const actualizarPerfilPaciente = (
    actualizarPerfilPacienteBody: ActualizarPerfilPacienteBody,
 signal?: AbortSignal
) => {


      return customInstance<ActualizarPerfilPaciente200>(
      {url: `/v1/paciente/actualizar_perfil`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: actualizarPerfilPacienteBody, signal
    },
      );
    }



export const getActualizarPerfilPacienteMutationOptions = <TError = ActualizarPerfilPaciente400 | ActualizarPerfilPaciente401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actualizarPerfilPaciente>>, TError,{data: ActualizarPerfilPacienteBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof actualizarPerfilPaciente>>, TError,{data: ActualizarPerfilPacienteBody}, TContext> => {

const mutationKey = ['actualizarPerfilPaciente'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof actualizarPerfilPaciente>>, {data: ActualizarPerfilPacienteBody}> = (props) => {
          const {data} = props ?? {};

          return  actualizarPerfilPaciente(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActualizarPerfilPacienteMutationResult = NonNullable<Awaited<ReturnType<typeof actualizarPerfilPaciente>>>
    export type ActualizarPerfilPacienteMutationBody = ActualizarPerfilPacienteBody
    export type ActualizarPerfilPacienteMutationError = ActualizarPerfilPaciente400 | ActualizarPerfilPaciente401

    /**
 * @summary Actualizar la información del perfil del paciente
 */
export const useActualizarPerfilPaciente = <TError = ActualizarPerfilPaciente400 | ActualizarPerfilPaciente401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actualizarPerfilPaciente>>, TError,{data: ActualizarPerfilPacienteBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof actualizarPerfilPaciente>>,
        TError,
        {data: ActualizarPerfilPacienteBody},
        TContext
      > => {
      return useMutation(getActualizarPerfilPacienteMutationOptions(options), queryClient);
    }
    /**
 * @summary Confirmar agendamiento y pagar anticipo
 */
export const crearCita = (
    crearCitaBody: CrearCitaBody,
 signal?: AbortSignal
) => {


      return customInstance<CrearCita201>(
      {url: `/v1/paciente/reservas/reservar_cita`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: crearCitaBody, signal
    },
      );
    }



export const getCrearCitaMutationOptions = <TError = CrearCita400 | CrearCita401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof crearCita>>, TError,{data: CrearCitaBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof crearCita>>, TError,{data: CrearCitaBody}, TContext> => {

const mutationKey = ['crearCita'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof crearCita>>, {data: CrearCitaBody}> = (props) => {
          const {data} = props ?? {};

          return  crearCita(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CrearCitaMutationResult = NonNullable<Awaited<ReturnType<typeof crearCita>>>
    export type CrearCitaMutationBody = CrearCitaBody
    export type CrearCitaMutationError = CrearCita400 | CrearCita401

    /**
 * @summary Confirmar agendamiento y pagar anticipo
 */
export const useCrearCita = <TError = CrearCita400 | CrearCita401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof crearCita>>, TError,{data: CrearCitaBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof crearCita>>,
        TError,
        {data: CrearCitaBody},
        TContext
      > => {
      return useMutation(getCrearCitaMutationOptions(options), queryClient);
    }
    /**
 * @summary Pagar el saldo de una transacción pendiente
 */
export const pagarTransaccionPendiente = (
    idTransaccion: string,
    pagarTransaccionPendienteBody: PagarTransaccionPendienteBody,
 signal?: AbortSignal
) => {


      return customInstance<PagarTransaccionPendiente200>(
      {url: `/v1/paciente/pagos/${idTransaccion}/pagar_pendiente`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pagarTransaccionPendienteBody, signal
    },
      );
    }



export const getPagarTransaccionPendienteMutationOptions = <TError = PagarTransaccionPendiente400 | PagarTransaccionPendiente401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pagarTransaccionPendiente>>, TError,{idTransaccion: string;data: PagarTransaccionPendienteBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof pagarTransaccionPendiente>>, TError,{idTransaccion: string;data: PagarTransaccionPendienteBody}, TContext> => {

const mutationKey = ['pagarTransaccionPendiente'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pagarTransaccionPendiente>>, {idTransaccion: string;data: PagarTransaccionPendienteBody}> = (props) => {
          const {idTransaccion,data} = props ?? {};

          return  pagarTransaccionPendiente(idTransaccion,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PagarTransaccionPendienteMutationResult = NonNullable<Awaited<ReturnType<typeof pagarTransaccionPendiente>>>
    export type PagarTransaccionPendienteMutationBody = PagarTransaccionPendienteBody
    export type PagarTransaccionPendienteMutationError = PagarTransaccionPendiente400 | PagarTransaccionPendiente401

    /**
 * @summary Pagar el saldo de una transacción pendiente
 */
export const usePagarTransaccionPendiente = <TError = PagarTransaccionPendiente400 | PagarTransaccionPendiente401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pagarTransaccionPendiente>>, TError,{idTransaccion: string;data: PagarTransaccionPendienteBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pagarTransaccionPendiente>>,
        TError,
        {idTransaccion: string;data: PagarTransaccionPendienteBody},
        TContext
      > => {
      return useMutation(getPagarTransaccionPendienteMutationOptions(options), queryClient);
    }
    /**
 * @summary Cancelar una cita programada
 */
export const cancelarCita = (
    idCita: string,
    cancelarCitaBody: CancelarCitaBody,
 signal?: AbortSignal
) => {


      return customInstance<CancelarCita200>(
      {url: `/v1/paciente/citas/${idCita}/cancelar`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: cancelarCitaBody, signal
    },
      );
    }



export const getCancelarCitaMutationOptions = <TError = CancelarCita400 | CancelarCita401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelarCita>>, TError,{idCita: string;data: CancelarCitaBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancelarCita>>, TError,{idCita: string;data: CancelarCitaBody}, TContext> => {

const mutationKey = ['cancelarCita'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelarCita>>, {idCita: string;data: CancelarCitaBody}> = (props) => {
          const {idCita,data} = props ?? {};

          return  cancelarCita(idCita,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CancelarCitaMutationResult = NonNullable<Awaited<ReturnType<typeof cancelarCita>>>
    export type CancelarCitaMutationBody = CancelarCitaBody
    export type CancelarCitaMutationError = CancelarCita400 | CancelarCita401

    /**
 * @summary Cancelar una cita programada
 */
export const useCancelarCita = <TError = CancelarCita400 | CancelarCita401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelarCita>>, TError,{idCita: string;data: CancelarCitaBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelarCita>>,
        TError,
        {idCita: string;data: CancelarCitaBody},
        TContext
      > => {
      return useMutation(getCancelarCitaMutationOptions(options), queryClient);
    }
