# Identificadores usados en la URL (Rutas)
id_cita_path:
  name: id_cita
  in: path
  required: true
  schema:
    type: string
    format: uuid

id_transaccion_path:
  name: id_transaccion
  in: path
  required: true
  schema:
    type: string
    format: uuid

id_paciente_path:
  name: id_paciente
  in: path
  required: true
  description: Identificador único del paciente
  schema:
    type: string
    format: uuid

# Identificadores usados como filtros (Query)
id_cita_query:
  name: id_cita
  in: query
  required: true
  description: ID de la cita a gestionar
  schema:
    type: string
    format: uuid

id_especialidad_query:
  name: id_especialidad
  in: query
  required: true
  schema:
    type: string

id_sucursal_query:
  name: id_sucursal
  in: query
  required: true
  schema:
    type: string

id_doctor_query:
  name: id_doctor
  in: query
  required: true
  schema:
    type: string

id_paciente_query:
  name: id_paciente
  in: query
  required: true
  description: Identificador único del paciente
  schema:
    type: string
    format: uuid

# Parámetros de tiempo y calendario
mes_query:
  name: mes
  in: query
  required: true
  schema:
    type: string
    example: "2026-03"

fecha_query:
  name: fecha
  in: query
  required: true
  schema:
    type: string

hora_query:
  name: hora
  in: query
  required: true
  schema:
    type: string

# Parámetros de paginación
limit_query:
  name: limit
  in: query
  description: "Cantidad de registros por página"
  schema:
    type: integer
    default: 5

page_query:
  name: page
  in: query
  description: "Número de página a consultar"
  schema:
    type: integer
    default: 1
