/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ObtenerAgendaDoctor200,
  ObtenerAgendaDoctor401,
  ObtenerDatosNuevaConsulta200,
  ObtenerDatosNuevaConsulta401,
  ObtenerDatosNuevaConsultaParams,
  ObtenerHistorialPacientePorDoctor200,
  ObtenerHistorialPacientePorDoctor401,
  ObtenerHistorialPacientePorDoctor404,
  ObtenerInicioDoctor200,
  ObtenerInicioDoctor401,
  ObtenerPacientesDoctor200,
  ObtenerPacientesDoctor401,
  ObtenerPagosDoctor200,
  ObtenerPagosDoctor401,
  ObtenerPerfilDoctor200,
  ObtenerPerfilDoctor401
} from '../model';

import { customInstance } from '.././axios-instance';




/**
 * @summary Obtener datos para la pantalla de inicio del doctor
 */
export const obtenerInicioDoctor = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerInicioDoctor200>(
      {url: `/v1/views/doctor/home`, method: 'GET', signal
    },
      );
    }




export const getObtenerInicioDoctorQueryKey = () => {
    return [
    `/v1/views/doctor/home`
    ] as const;
    }


export const getObtenerInicioDoctorQueryOptions = <TData = Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError = ObtenerInicioDoctor401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerInicioDoctorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerInicioDoctor>>> = ({ signal }) => obtenerInicioDoctor(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerInicioDoctorQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerInicioDoctor>>>
export type ObtenerInicioDoctorQueryError = ObtenerInicioDoctor401


export function useObtenerInicioDoctor<TData = Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError = ObtenerInicioDoctor401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerInicioDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerInicioDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerInicioDoctor<TData = Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError = ObtenerInicioDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerInicioDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerInicioDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerInicioDoctor<TData = Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError = ObtenerInicioDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener datos para la pantalla de inicio del doctor
 */

export function useObtenerInicioDoctor<TData = Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError = ObtenerInicioDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerInicioDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerInicioDoctorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Obtener la información del perfil del doctor
 */
export const obtenerPerfilDoctor = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerPerfilDoctor200>(
      {url: `/v1/views/doctor/perfil_doctor`, method: 'GET', signal
    },
      );
    }




export const getObtenerPerfilDoctorQueryKey = () => {
    return [
    `/v1/views/doctor/perfil_doctor`
    ] as const;
    }


export const getObtenerPerfilDoctorQueryOptions = <TData = Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError = ObtenerPerfilDoctor401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerPerfilDoctorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerPerfilDoctor>>> = ({ signal }) => obtenerPerfilDoctor(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerPerfilDoctorQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerPerfilDoctor>>>
export type ObtenerPerfilDoctorQueryError = ObtenerPerfilDoctor401


export function useObtenerPerfilDoctor<TData = Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError = ObtenerPerfilDoctor401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerPerfilDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerPerfilDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerPerfilDoctor<TData = Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError = ObtenerPerfilDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerPerfilDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerPerfilDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerPerfilDoctor<TData = Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError = ObtenerPerfilDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener la información del perfil del doctor
 */

export function useObtenerPerfilDoctor<TData = Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError = ObtenerPerfilDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPerfilDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerPerfilDoctorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Obtener la agenda de citas del día y posteriores
 */
export const obtenerAgendaDoctor = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerAgendaDoctor200>(
      {url: `/v1/views/doctor/agenda_proximas`, method: 'GET', signal
    },
      );
    }




export const getObtenerAgendaDoctorQueryKey = () => {
    return [
    `/v1/views/doctor/agenda_proximas`
    ] as const;
    }


export const getObtenerAgendaDoctorQueryOptions = <TData = Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError = ObtenerAgendaDoctor401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerAgendaDoctorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerAgendaDoctor>>> = ({ signal }) => obtenerAgendaDoctor(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerAgendaDoctorQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerAgendaDoctor>>>
export type ObtenerAgendaDoctorQueryError = ObtenerAgendaDoctor401


export function useObtenerAgendaDoctor<TData = Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError = ObtenerAgendaDoctor401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerAgendaDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerAgendaDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerAgendaDoctor<TData = Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError = ObtenerAgendaDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerAgendaDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerAgendaDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerAgendaDoctor<TData = Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError = ObtenerAgendaDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener la agenda de citas del día y posteriores
 */

export function useObtenerAgendaDoctor<TData = Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError = ObtenerAgendaDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAgendaDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerAgendaDoctorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Obtener el directorio de pacientes atendidos
 */
export const obtenerPacientesDoctor = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerPacientesDoctor200>(
      {url: `/v1/views/doctor/pacientes`, method: 'GET', signal
    },
      );
    }




export const getObtenerPacientesDoctorQueryKey = () => {
    return [
    `/v1/views/doctor/pacientes`
    ] as const;
    }


export const getObtenerPacientesDoctorQueryOptions = <TData = Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError = ObtenerPacientesDoctor401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerPacientesDoctorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerPacientesDoctor>>> = ({ signal }) => obtenerPacientesDoctor(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerPacientesDoctorQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerPacientesDoctor>>>
export type ObtenerPacientesDoctorQueryError = ObtenerPacientesDoctor401


export function useObtenerPacientesDoctor<TData = Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError = ObtenerPacientesDoctor401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerPacientesDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerPacientesDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerPacientesDoctor<TData = Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError = ObtenerPacientesDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerPacientesDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerPacientesDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerPacientesDoctor<TData = Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError = ObtenerPacientesDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener el directorio de pacientes atendidos
 */

export function useObtenerPacientesDoctor<TData = Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError = ObtenerPacientesDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPacientesDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerPacientesDoctorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Ver el historial de consultas de un paciente específico
 */
export const obtenerHistorialPacientePorDoctor = (
    idPaciente: string,
 signal?: AbortSignal
) => {


      return customInstance<ObtenerHistorialPacientePorDoctor200>(
      {url: `/v1/views/doctor/pacientes/${idPaciente}/historial_paciente`, method: 'GET', signal
    },
      );
    }




export const getObtenerHistorialPacientePorDoctorQueryKey = (idPaciente: string,) => {
    return [
    `/v1/views/doctor/pacientes/${idPaciente}/historial_paciente`
    ] as const;
    }


export const getObtenerHistorialPacientePorDoctorQueryOptions = <TData = Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError = ObtenerHistorialPacientePorDoctor401 | ObtenerHistorialPacientePorDoctor404>(idPaciente: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerHistorialPacientePorDoctorQueryKey(idPaciente);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>> = ({ signal }) => obtenerHistorialPacientePorDoctor(idPaciente, signal);





   return  { queryKey, queryFn, enabled: !!(idPaciente), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerHistorialPacientePorDoctorQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>>
export type ObtenerHistorialPacientePorDoctorQueryError = ObtenerHistorialPacientePorDoctor401 | ObtenerHistorialPacientePorDoctor404


export function useObtenerHistorialPacientePorDoctor<TData = Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError = ObtenerHistorialPacientePorDoctor401 | ObtenerHistorialPacientePorDoctor404>(
 idPaciente: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerHistorialPacientePorDoctor<TData = Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError = ObtenerHistorialPacientePorDoctor401 | ObtenerHistorialPacientePorDoctor404>(
 idPaciente: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerHistorialPacientePorDoctor<TData = Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError = ObtenerHistorialPacientePorDoctor401 | ObtenerHistorialPacientePorDoctor404>(
 idPaciente: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ver el historial de consultas de un paciente específico
 */

export function useObtenerHistorialPacientePorDoctor<TData = Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError = ObtenerHistorialPacientePorDoctor401 | ObtenerHistorialPacientePorDoctor404>(
 idPaciente: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerHistorialPacientePorDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerHistorialPacientePorDoctorQueryOptions(idPaciente,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Cargar datos previos para llenar un nuevo expediente clínico
 */
export const obtenerDatosNuevaConsulta = (
    params: ObtenerDatosNuevaConsultaParams,
 signal?: AbortSignal
) => {


      return customInstance<ObtenerDatosNuevaConsulta200>(
      {url: `/v1/views/doctor/nuevo_expediente`, method: 'GET',
        params, signal
    },
      );
    }




export const getObtenerDatosNuevaConsultaQueryKey = (params?: ObtenerDatosNuevaConsultaParams,) => {
    return [
    `/v1/views/doctor/nuevo_expediente`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerDatosNuevaConsultaQueryOptions = <TData = Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError = ObtenerDatosNuevaConsulta401>(params: ObtenerDatosNuevaConsultaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerDatosNuevaConsultaQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>> = ({ signal }) => obtenerDatosNuevaConsulta(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerDatosNuevaConsultaQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>>
export type ObtenerDatosNuevaConsultaQueryError = ObtenerDatosNuevaConsulta401


export function useObtenerDatosNuevaConsulta<TData = Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError = ObtenerDatosNuevaConsulta401>(
 params: ObtenerDatosNuevaConsultaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>,
          TError,
          Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerDatosNuevaConsulta<TData = Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError = ObtenerDatosNuevaConsulta401>(
 params: ObtenerDatosNuevaConsultaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>,
          TError,
          Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerDatosNuevaConsulta<TData = Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError = ObtenerDatosNuevaConsulta401>(
 params: ObtenerDatosNuevaConsultaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Cargar datos previos para llenar un nuevo expediente clínico
 */

export function useObtenerDatosNuevaConsulta<TData = Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError = ObtenerDatosNuevaConsulta401>(
 params: ObtenerDatosNuevaConsultaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerDatosNuevaConsulta>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerDatosNuevaConsultaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Ver ingresos y transacciones recientes del médico
 */
export const obtenerPagosDoctor = (

 signal?: AbortSignal
) => {


      return customInstance<ObtenerPagosDoctor200>(
      {url: `/v1/views/doctor/pagos`, method: 'GET', signal
    },
      );
    }




export const getObtenerPagosDoctorQueryKey = () => {
    return [
    `/v1/views/doctor/pagos`
    ] as const;
    }


export const getObtenerPagosDoctorQueryOptions = <TData = Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError = ObtenerPagosDoctor401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerPagosDoctorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerPagosDoctor>>> = ({ signal }) => obtenerPagosDoctor(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerPagosDoctorQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerPagosDoctor>>>
export type ObtenerPagosDoctorQueryError = ObtenerPagosDoctor401


export function useObtenerPagosDoctor<TData = Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError = ObtenerPagosDoctor401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerPagosDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerPagosDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerPagosDoctor<TData = Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError = ObtenerPagosDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerPagosDoctor>>,
          TError,
          Awaited<ReturnType<typeof obtenerPagosDoctor>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerPagosDoctor<TData = Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError = ObtenerPagosDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ver ingresos y transacciones recientes del médico
 */

export function useObtenerPagosDoctor<TData = Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError = ObtenerPagosDoctor401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerPagosDoctor>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerPagosDoctorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






