/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Atria API - Sistema de Gestión Médica
 * Documentación oficial de las APIs bajo el patrón BFF para los portales de paciente y doctor de Atria.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1DoctorExportarPagos200,
  GetV1DoctorExportarPagos401,
  GetV1DoctorExportarPagosParams,
  PostV1DoctorBloquearAgenda200,
  PostV1DoctorBloquearAgenda400,
  PostV1DoctorBloquearAgenda401,
  PostV1DoctorBloquearAgenda409,
  PostV1DoctorBloquearAgendaBody,
  PostV1DoctorGuardarExpediente201,
  PostV1DoctorGuardarExpediente400,
  PostV1DoctorGuardarExpediente401,
  PostV1DoctorGuardarExpedienteBody,
  PutV1DoctorEditarPerfil200,
  PutV1DoctorEditarPerfil400,
  PutV1DoctorEditarPerfil401,
  PutV1DoctorEditarPerfilBody
} from '../model';

import { customInstance } from '.././axios-instance';




/**
 * @summary Guardar y Firmar Expediente Clínico
 */
export const postV1DoctorGuardarExpediente = (
    postV1DoctorGuardarExpedienteBody: PostV1DoctorGuardarExpedienteBody,
 signal?: AbortSignal
) => {


      return customInstance<PostV1DoctorGuardarExpediente201>(
      {url: `/v1/doctor/guardar_expediente`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1DoctorGuardarExpedienteBody, signal
    },
      );
    }



export const getPostV1DoctorGuardarExpedienteMutationOptions = <TError = PostV1DoctorGuardarExpediente400 | PostV1DoctorGuardarExpediente401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1DoctorGuardarExpediente>>, TError,{data: PostV1DoctorGuardarExpedienteBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1DoctorGuardarExpediente>>, TError,{data: PostV1DoctorGuardarExpedienteBody}, TContext> => {

const mutationKey = ['postV1DoctorGuardarExpediente'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1DoctorGuardarExpediente>>, {data: PostV1DoctorGuardarExpedienteBody}> = (props) => {
          const {data} = props ?? {};

          return  postV1DoctorGuardarExpediente(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1DoctorGuardarExpedienteMutationResult = NonNullable<Awaited<ReturnType<typeof postV1DoctorGuardarExpediente>>>
    export type PostV1DoctorGuardarExpedienteMutationBody = PostV1DoctorGuardarExpedienteBody
    export type PostV1DoctorGuardarExpedienteMutationError = PostV1DoctorGuardarExpediente400 | PostV1DoctorGuardarExpediente401

    /**
 * @summary Guardar y Firmar Expediente Clínico
 */
export const usePostV1DoctorGuardarExpediente = <TError = PostV1DoctorGuardarExpediente400 | PostV1DoctorGuardarExpediente401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1DoctorGuardarExpediente>>, TError,{data: PostV1DoctorGuardarExpedienteBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1DoctorGuardarExpediente>>,
        TError,
        {data: PostV1DoctorGuardarExpedienteBody},
        TContext
      > => {
      return useMutation(getPostV1DoctorGuardarExpedienteMutationOptions(options), queryClient);
    }
    /**
 * @summary Bloquear Horario (Ajustes de disponibilidad)
 */
export const postV1DoctorBloquearAgenda = (
    postV1DoctorBloquearAgendaBody: PostV1DoctorBloquearAgendaBody,
 signal?: AbortSignal
) => {


      return customInstance<PostV1DoctorBloquearAgenda200>(
      {url: `/v1/doctor/bloquear_agenda`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1DoctorBloquearAgendaBody, signal
    },
      );
    }



export const getPostV1DoctorBloquearAgendaMutationOptions = <TError = PostV1DoctorBloquearAgenda400 | PostV1DoctorBloquearAgenda401 | PostV1DoctorBloquearAgenda409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1DoctorBloquearAgenda>>, TError,{data: PostV1DoctorBloquearAgendaBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1DoctorBloquearAgenda>>, TError,{data: PostV1DoctorBloquearAgendaBody}, TContext> => {

const mutationKey = ['postV1DoctorBloquearAgenda'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1DoctorBloquearAgenda>>, {data: PostV1DoctorBloquearAgendaBody}> = (props) => {
          const {data} = props ?? {};

          return  postV1DoctorBloquearAgenda(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1DoctorBloquearAgendaMutationResult = NonNullable<Awaited<ReturnType<typeof postV1DoctorBloquearAgenda>>>
    export type PostV1DoctorBloquearAgendaMutationBody = PostV1DoctorBloquearAgendaBody
    export type PostV1DoctorBloquearAgendaMutationError = PostV1DoctorBloquearAgenda400 | PostV1DoctorBloquearAgenda401 | PostV1DoctorBloquearAgenda409

    /**
 * @summary Bloquear Horario (Ajustes de disponibilidad)
 */
export const usePostV1DoctorBloquearAgenda = <TError = PostV1DoctorBloquearAgenda400 | PostV1DoctorBloquearAgenda401 | PostV1DoctorBloquearAgenda409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1DoctorBloquearAgenda>>, TError,{data: PostV1DoctorBloquearAgendaBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1DoctorBloquearAgenda>>,
        TError,
        {data: PostV1DoctorBloquearAgendaBody},
        TContext
      > => {
      return useMutation(getPostV1DoctorBloquearAgendaMutationOptions(options), queryClient);
    }
    /**
 * @summary Exportar historial de pagos del mes
 */
export const getV1DoctorExportarPagos = (
    params: GetV1DoctorExportarPagosParams,
 signal?: AbortSignal
) => {


      return customInstance<GetV1DoctorExportarPagos200>(
      {url: `/v1/doctor/exportar_pagos`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetV1DoctorExportarPagosQueryKey = (params?: GetV1DoctorExportarPagosParams,) => {
    return [
    `/v1/doctor/exportar_pagos`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1DoctorExportarPagosQueryOptions = <TData = Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError = GetV1DoctorExportarPagos401>(params: GetV1DoctorExportarPagosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1DoctorExportarPagosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1DoctorExportarPagos>>> = ({ signal }) => getV1DoctorExportarPagos(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1DoctorExportarPagosQueryResult = NonNullable<Awaited<ReturnType<typeof getV1DoctorExportarPagos>>>
export type GetV1DoctorExportarPagosQueryError = GetV1DoctorExportarPagos401


export function useGetV1DoctorExportarPagos<TData = Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError = GetV1DoctorExportarPagos401>(
 params: GetV1DoctorExportarPagosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1DoctorExportarPagos>>,
          TError,
          Awaited<ReturnType<typeof getV1DoctorExportarPagos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1DoctorExportarPagos<TData = Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError = GetV1DoctorExportarPagos401>(
 params: GetV1DoctorExportarPagosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1DoctorExportarPagos>>,
          TError,
          Awaited<ReturnType<typeof getV1DoctorExportarPagos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1DoctorExportarPagos<TData = Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError = GetV1DoctorExportarPagos401>(
 params: GetV1DoctorExportarPagosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Exportar historial de pagos del mes
 */

export function useGetV1DoctorExportarPagos<TData = Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError = GetV1DoctorExportarPagos401>(
 params: GetV1DoctorExportarPagosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1DoctorExportarPagos>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1DoctorExportarPagosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Actualizar información de contacto del perfil
 */
export const putV1DoctorEditarPerfil = (
    putV1DoctorEditarPerfilBody: PutV1DoctorEditarPerfilBody,
 signal?: AbortSignal
) => {


      return customInstance<PutV1DoctorEditarPerfil200>(
      {url: `/v1/doctor/editar_perfil`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putV1DoctorEditarPerfilBody, signal
    },
      );
    }



export const getPutV1DoctorEditarPerfilMutationOptions = <TError = PutV1DoctorEditarPerfil400 | PutV1DoctorEditarPerfil401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putV1DoctorEditarPerfil>>, TError,{data: PutV1DoctorEditarPerfilBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putV1DoctorEditarPerfil>>, TError,{data: PutV1DoctorEditarPerfilBody}, TContext> => {

const mutationKey = ['putV1DoctorEditarPerfil'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putV1DoctorEditarPerfil>>, {data: PutV1DoctorEditarPerfilBody}> = (props) => {
          const {data} = props ?? {};

          return  putV1DoctorEditarPerfil(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutV1DoctorEditarPerfilMutationResult = NonNullable<Awaited<ReturnType<typeof putV1DoctorEditarPerfil>>>
    export type PutV1DoctorEditarPerfilMutationBody = PutV1DoctorEditarPerfilBody
    export type PutV1DoctorEditarPerfilMutationError = PutV1DoctorEditarPerfil400 | PutV1DoctorEditarPerfil401

    /**
 * @summary Actualizar información de contacto del perfil
 */
export const usePutV1DoctorEditarPerfil = <TError = PutV1DoctorEditarPerfil400 | PutV1DoctorEditarPerfil401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putV1DoctorEditarPerfil>>, TError,{data: PutV1DoctorEditarPerfilBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putV1DoctorEditarPerfil>>,
        TError,
        {data: PutV1DoctorEditarPerfilBody},
        TContext
      > => {
      return useMutation(getPutV1DoctorEditarPerfilMutationOptions(options), queryClient);
    }
